name: rjd-sunwait
title: Sunwait
version: '0.9.1' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Calculates sun-up/down times with twilights.
description: |
            'Sunwait calculates sunrise or sunset times with civil, nautical, astronomical and custom twilights, for use with Windows Task Scheduler or 'cron' on Linux.'
              The description above refers to the software: https://github.com/risacher/sunwait.git
            * I have packaged the software as a snap for **personal use** but I have made the snap available for free.
            * I do not maintain the software itself. I only maintain the snap. Please report software bugs to the maintainers.
            * Report snap-specific bugs to me.
            * I _DO NOT_ use this snap. It _has been tested_ on my system.
            * Packaging 'style' : git build for linux machines.
            * License refers to the original software, not the snapcraft 'code'.
            * More info:
            * Run the following to rename the snap
            ```sudo snap alias rjd-sunwait.sunwait sunwait```

website: https://github.com/RJDan/sunwait_snap
source-code : https://github.com/RJDan/sunwait_snap
icon: Icon_230615.svg

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
license: GPL-3.0
base: core22 # the base snap is the execution environment for this snap
architectures:
    - amd64

apps:
    sunwait:
        command: usr/bin/sunwait
        plugs:
          - home
          - network

parts:
    sunwait:
        source: https://github.com/risacher/sunwait.git
        source-type: git
        source-tag: "0.9.1"
        # See 'snapcraft plugins'
        plugin: make
        organize:
            "Icon_230615.svg" : snap/Icon_230615.svg
            "sunwait" : usr/bin/sunwait
        override-build: |
            make
            #   cp ./sunwait ${SNAPCRAFT_PART_INSTALL}/
            cp ${SNAPCRAFT_PART_BUILD}/sunwait ${SNAPCRAFT_PART_INSTALL}/sunwait
        stage:
                - usr/bin
        prime:
                - usr/bin

